name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    run-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Instala o Node
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    # Passo 1: Instalar as dependências NPM/Yarn
    - name: Install dependencies
      run: npm install

    # Passo 2: Executar a build
    - name: Run build
      run: npm run build

    # Passo 3: Copiar código para a Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secret.SSH_HOST }}
        username: {{ secrets.SSH_USERNAME }}
        port: {{ secrets.SSH_PORT }}
        key: {{ secrets.SSH_KEY }}
        source: "., !node_modules"   
        target: "~/uniformSystem/backend" 

    # Passo 4: Executar "yarn" na Digital Ocean para instalar as dependências
    # Passo 5: Executar as migrations do Typeorm
    # Passo 6: Restart no servidor Node.js
    - name: Run production scripts
      uses: apple/ssh-action@master
      with:
				host: ${{ secret.SSH_HOST }}
				username: ${{ secrets.SSH_USERNAME }}
				port: ${{ secrets.SSH_PORT }}
				key: ${{ secrets.SSH_KEY }}
				script: | 
				 cd ~/uniformSystem/backend
				 npm install
				 npm knex migrate:latest
				 pm2 restart uniformsystem-backend
