name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Instala o Node
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
       node-version: 12.x
        
    # Passo 1: Cache para Dependências do projeto
    - name: Do cache from dependencies
      uses: actions/cache@v2
      with:
        path: ./
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
         ${{ runner.os }}-node-:

    # Passo 2: Install Instalar as dependências NPM/Yarn     
    - name: Do cache from dependencies
      run: npm install

    # Passo 3: Copiar código para a Digital Ocean
    - name: Copy files to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/uniformSystem/backend"
  
    # Passo 4: Entra na pasta, instala, roda migrations e restarta o pm2 (para manter rodando)
    - name: Run production script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: | 
         cd ~/uniformSystem/backend
         npm install
         npx knex migrate:latest
         pm2 restart uniformsystem-backend
